# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
    ]
