# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance actual'),
        ),
    ]
