# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_auto_20171208_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date_time',), 'verbose_name': 'Transacci\xf3n', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
